<?php

/**
 * @file
 * Contains vidyard.module.
 */

use Drupal\Core\Field\FormatterInterface;
use Drupal\Core\Field\FieldDefinitionInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function vidyard_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the Vidyard module.
    case 'help.page.vidyard':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('A Media source and oEmbed provider for the Vidyard video platform.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_media_source_info_alter().
 */
function vidyard_media_source_info_alter(array &$sources) {
  // Add Vidyard as an available provider for the Remote Video media source.
  $sources['oembed:video']['providers'][] = "Vidyard";
}

/**
 * Implements hook_field_formatter_third_party_settings_form().
 */
function vidyard_field_formatter_third_party_settings_form(FormatterInterface $plugin, FieldDefinitionInterface $field_definition, $view_mode, $form, FormStateInterface $form_state) {
  $element = array();

  // Add a setting to enable Vidyard's responsive embed code to the oEmbed field
  // display formatter options form.
  if ($plugin->getPluginId() == 'oembed') {
    $element = [
      'vidyard_responsive' => [
        '#type' => 'checkbox',
        '#title' => t('Use responsive embed code for Vidyard videos'),
        '#default_value' => $plugin->getThirdPartySetting('vidyard', 'vidyard_responsive'),
      ],
    ];
  }
  return $element;
}

/**
 * Implements hook_field_formatter_settings_summary_alter().
 */
function vidyard_field_formatter_settings_summary_alter(&$summary, $context) {
  // Add a line to the oEmbed field formatter settings summary to indicate that
  // Vidyard's responsive embed code setting is enabled.
  /** @var \Drupal\Core\Field\FormatterInterface $formatter */
  $formatter = $context['formatter'];
  if ($formatter->getPluginId() == 'oembed') {
    if ($formatter->getThirdPartySetting('vidyard', 'vidyard_responsive')) {
      $summary[] = t('Responsive embed enabled for Vidyard videos.');
    }
  }
}
